version: '3.5'
services:
  adminer:
    container_name: adminer
    build: requirements/bonus/adminer/.
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    restart: unless-stopped
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "${MYDB_USER}", "-p${MYDB_PASSWORD}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    container_name: nginx
    build: requirements/nginx/.
    restart: unless-stopped
    volumes:
      - WordPress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - WordPress:/var/www/html/
    networks:
      - mynetwork
    expose:
      - "9000"
    env_file:
      - .env

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mriant/data/database/

  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mriant/data/website