version: '3.5'
services:
  adminer:
    container_name: adminer
    build: requirements/bonus/adminer/.
    restart: always
    ports:
      - "80:80"
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    restart: always
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mriant/data/database/